### ISSUE TITLE
Robustly stopping Async Computation External Package + try Statement

### ISSUE THREAD

**Issue by karchjd** [fellstat/ShinyAsyncTools#25]
Hey,

thanks so much for this great package! I am creating a shinyapp (https://github.com/karchjd/lavaangui) that runs one potentially long-running function from a package (`lavaan`) that I do not maintain, thus, I do not have access to it. What makes matters worse is that the long-running code is enclosed in a try statement. So, I can't seem to use `stop` to abort. I also cannot use `stopMulticoreFuture` because I have to use `plan(multisession)` because I need the app to work on Windows as well. 

The only viable solution I came up with is to inject code into the existing package, which calls `quit()` if the user presses cancel. The code below demonstrates my approach. While this is a rather ugly solution, it seems to work most of the time. Using only one browser, I am not able to crash my app. However, when I run loads of end-to-end tests on my app (see https://github.com/karchjd/lavaangui/blob/main/src/e2e/example.spec.ts), the server eventually crashes with error:

```
Error: ‘inherits(future, "Future")’ is not TRUE
```

Unfortunately, I could not yet isolate the sequences of events that lead the server to crash. I highly suspect that this has to do with how I abort the future (with quit). I am thus wondering whether you have an idea for a cleaner way to abort the future given my constraints. I am thinking of something like a supper error, which ignores all try statements and propagates the error anyway but don't think such a concept exists.

Example:

```
library(promises)
library(future)
library(shiny)
library(lavaan)
plan(multisession)


ui <- fluidPage(
  titlePanel("Cancelable Async Task"),
  
  sidebarLayout(
    sidebarPanel(
      actionButton('run', 'Run'),
      actionButton('cancel', 'Cancel')
    ),
    
    mainPanel(
      textOutput("result")
    )
  )
)

server <- function(input, output, session) {
  
  # state vars
  abort_file <- NULL
  result_val <- reactiveVal()
  
  # main code for running long task
  observeEvent(input$run, {
    print("Starting Run")
    abort_file <<- tempfile()
    
    fut <- promises::future_promise({
      #insert abort code into existing function
      original_function_string <- deparse(utils::getFromNamespace('lav_model_objective', 'lavaan'))
      new_function <- append(original_function_string, "if (file.exists(abort_file)) {quit()}", after = 3)
      new_function <- eval(parse(text = new_function))
      environment(new_function) <- asNamespace('lavaan')
      utils::assignInNamespace("lav_model_objective", new_function, ns = "lavaan")
      
      #run long running computation
      HS.model <- ' visual  =~ x1 + x2 + x3
              textual =~ x4 + x5 + x6
              speed   =~ x7 + x8 + x9 '
      fit <- cfa(HS.model, se = "bootstrap", data = HolzingerSwineford1939)
      sum <- summary(fit)
    }, packages = "lavaan", globals = c("abort_file", "model", "lavaan_string"), seed = TRUE)
    prom <- fut %...>% result_val
    prom <- promises::catch(fut,
                            function(e){
                              result_val(NULL)
                              session$sendCustomMessage("lav_failed", "lav_error")
                              to_render("stopped by user")
                            })
    prom <- promises::finally(prom, function(){
      print("finished run")
      if(file.exists(abort_file)){
        file.remove(abort_file)  
      }
    })
    return(NULL) 
  })
  
  
  observeEvent(input$cancel,{
    print('canceling')
    file.create(abort_file)
  })
  
  output$result <- renderPrint({
    req(result_val())
  })
}

app <- shinyApp(ui = ui, server = server)
runApp(app, launch.browser = TRUE)
```

**Comment by ifellows** [comment]
I have not run your end to end tests, so I can't say for certain what the solution should be. I'm not surprised that using `quit` didn't work as this kills the session, which I would expect to mess up your multisession plan.

Does replacing `quit()` with `rlang::interrupt()` resolve the issue?

**Comment by karchjd** [comment]
Sorry for not getting back to you earlier. I had to work on different projects and only now had time to follow up on this.

The `rlang::interrupt` idea seems excellent. Thank you!!! I was not aware of this function. 

Unfortunately, I can't get it to work fully. So, any additional input would be greatly appreciated. I replaced `quit()` with `rlang::interrupt()`. This seems to interrupt the computation but neither `promises::catch` nor `promises::finally` seem to be executed afterwards. So, I can't communicate anymore to the parent process that the user interupted the computation. Do you have an idea how to do this? Although, I find it a bit strange that after `quit()` `promises::catch` works but not after `interrrupt`. So, maybe something else is going on. The behavior I see is that the promise is stopped (after interrupt there is no iteration in my log anymore) but neither the print from catch or finally is displayed.

Updated code is below:

```
library(promises)
library(future)
library(shiny)
library(lavaan)
plan(multisession)


ui <- fluidPage(
  titlePanel("Cancelable Async Task"),
  
  sidebarLayout(
    sidebarPanel(
      actionButton('run', 'Run'),
      actionButton('cancel', 'Cancel')
    ),
    
    mainPanel(
      textOutput("result")
    )
  )
)

server <- function(input, output, session) {
  
  # state vars
  abort_file <- NULL
  result_val <- reactiveVal()
  
  # Setup log file
  log_file <- tempfile(fileext = ".log")
  cat("Logging in ")
  cat(log_file)
  
  # Logging function
  log_message <- function(message) {
    timestamp <- format(Sys.time(), "%Y-%m-%d %H:%M:%S")
    message_to_log <- paste(timestamp, message, sep=" - ")
    write(message_to_log, log_file, append = TRUE)
  }
  
  log_message("hallo")
  # main code for running long task
  observeEvent(input$run, {
    print("Starting Run")
    abort_file <<- tempfile()
    print("before future")
    fut <- promises::future_promise({
      #insert abort code into existing function
      original_function_string <- deparse(utils::getFromNamespace('lav_model_objective', 'lavaan'))
      new_function <- append(original_function_string, "if (file.exists(abort_file)) {log_message(\"interrupt\");rlang::interrupt()}", after = 3)
      new_function <- append(new_function, "log_message(\"iteration\")", after = 3)
      new_function <- eval(parse(text = new_function))
      environment(new_function) <- asNamespace('lavaan')
      utils::assignInNamespace("lav_model_objective", new_function, ns = "lavaan")
      
      #run long running computation
      HS.model <- ' visual  =~ x1 + x2 + x3
              textual =~ x4 + x5 + x6
              speed   =~ x7 + x8 + x9 '
      log_message("fitting")
      fit <- cfa(HS.model, se = "bootstrap", data = HolzingerSwineford1939)
      log_message("finished fitting")
      sum <- summary(fit)
    }, packages = "lavaan", globals = c("abort_file", "model", "lavaan_string", "log_file", "log_message"), seed = TRUE)
    prom <- fut %...>% result_val
    prom <- promises::catch(fut,
                            function(e){
                              result_val(NULL)
                              print("cancelled")
                            })
    prom <- promises::finally(prom, function(){
      print("finished run")
      if(file.exists(abort_file)){
        file.remove(abort_file)  
      }
    })
    return(NULL) 
  })
  
  
  observeEvent(input$cancel,{
    print('canceling')
    file.create(abort_file)
  })
  
  output$result <- renderPrint({
    req(result_val())
  })
}

app <- shinyApp(ui = ui, server = server)
runApp(app, launch.browser = TRUE)
```

**Comment by ifellows** [comment]
This is a bit outside the scope of the ipc codebase, so I'm closing this issue. As potential directions, I suggest you look at either calling `on.exit` within the promise to do the cleanup or using `ipc` to communicate that the canceling has taken place just before calling `interrupt`.
